-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-15 18:50:44 GMT+02:00
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE TABLE bankaccount (
    account_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL,
    card_number       VARCHAR2(16) NOT NULL,
    expiring_date     DATE NOT NULL,
    cvv_code          NUMBER(3) NOT NULL,
    account_balance   NUMBER(10) NOT NULL,
    users_user_id     NUMBER(10) NOT NULL
);

ALTER TABLE bankaccount ADD CONSTRAINT bankaccount_pk PRIMARY KEY ( account_id );

ALTER TABLE bankaccount ADD CONSTRAINT bankaccount_card_number_un UNIQUE ( card_number );

CREATE TABLE parking_lot (
    lot_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL,
    floor_no       NUMBER(3),
    availability   CHAR(1)
);

ALTER TABLE parking_lot ADD CONSTRAINT parking_lot_pk PRIMARY KEY ( lot_id );

CREATE TABLE parking_subscription (
    subs_id              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL,
    expiring_date        DATE,
    users_user_id        NUMBER(10) NOT NULL,
    parking_lot_lot_id   NUMBER(10) NOT NULL
);

ALTER TABLE parking_subscription ADD CONSTRAINT parking_subscription_pk PRIMARY KEY ( subs_id );

CREATE TABLE prices (
    price_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL,
    day_price     NUMBER(10),
    night_price   NUMBER(10)
);

ALTER TABLE prices
    ADD CONSTRAINT day_price_check CHECK ( day_price BETWEEN 5 AND 20 );

ALTER TABLE prices ADD CHECK ( night_price BETWEEN 1 AND 5 );

ALTER TABLE prices ADD CONSTRAINT prices_pk PRIMARY KEY ( price_id );

ALTER TABLE prices ADD CONSTRAINT prices_price_id_un UNIQUE ( price_id );

CREATE TABLE tickets (
    ticket_id            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL,
    ticket_code          VARCHAR2(20),
    floor_no             NUMBER(3),
    parking_lot_lot_id   NUMBER(10) NOT NULL
);

ALTER TABLE tickets ADD CONSTRAINT tickets_pk PRIMARY KEY ( ticket_id );

CREATE TABLE users (
    user_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL,
    username   VARCHAR2(20),
    password   VARCHAR2(20),
    email      VARCHAR2(30)
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

ALTER TABLE users ADD CONSTRAINT users_username_email_un UNIQUE ( username,
                                                                  email );

ALTER TABLE bankaccount
    ADD CONSTRAINT bankaccount_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE parking_subscription
    ADD CONSTRAINT parking_subscription_parking_lot_fk FOREIGN KEY ( parking_lot_lot_id )
        REFERENCES parking_lot ( lot_id );

ALTER TABLE parking_subscription
    ADD CONSTRAINT parking_subscription_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE tickets
    ADD CONSTRAINT tickets_parking_lot_fk FOREIGN KEY ( parking_lot_lot_id )
        REFERENCES parking_lot ( lot_id );

CREATE SEQUENCE bankaccount_account_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE parking_lot_lot_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE parking_subscription_subs_id START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE prices_price_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE tickets_ticket_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE users_user_id_seq START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
